# coding: utf-8

"""
    Sonatype Nexus IQ Server

    This documents the available APIs into [Sonatype Nexus IQ Server](https://www.sonatype.com/products/open-source-security-dependency-management) (also knwon as Nexus Lifecycle).   # noqa: E501

    OpenAPI spec version: 156
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import nexus_iq_sdk
from nexus_iq_sdk.models.component_obligation_attribution_dto import (  # noqa: E501
    ComponentObligationAttributionDTO,
)
from nexus_iq_sdk.rest import ApiException


class TestComponentObligationAttributionDTO(unittest.TestCase):
    """ComponentObligationAttributionDTO unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testComponentObligationAttributionDTO(self):
        """Test ComponentObligationAttributionDTO"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.component_obligation_attribution_dto.ComponentObligationAttributionDTO()  # noqa: E501
        pass


if __name__ == "__main__":
    unittest.main()
