"""
    Sonatype Nexus IQ Server

    This documents the available APIs into [Sonatype Nexus IQ Server](https://www.sonatype.com/products/open-source-security-dependency-management) (also knwon as Nexus Lifecycle).   # noqa: E501

    OpenAPI spec version: 156

    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import unittest

import nexus_iq_sdk
from nexus_iq_sdk.models.attribution_report_template_dto import (  # noqa: E501
    AttributionReportTemplateDTO,
)
from nexus_iq_sdk.rest import ApiException


class TestAttributionReportTemplateDTO(unittest.TestCase):
    """AttributionReportTemplateDTO unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAttributionReportTemplateDTO(self):
        """Test AttributionReportTemplateDTO"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.attribution_report_template_dto.AttributionReportTemplateDTO()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
