# coding: utf-8

"""
    Sonatype Nexus IQ Server

    This documents the available APIs into [Sonatype Nexus IQ Server](https://www.sonatype.com/products/open-source-security-dependency-management) (also knwon as Nexus Lifecycle).   # noqa: E501

    OpenAPI spec version: 156
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import nexus_iq_sdk
from nexus_iq_sdk.api.config_jira_api import ConfigJIRAApi  # noqa: E501
from nexus_iq_sdk.rest import ApiException


class TestConfigJIRAApi(unittest.TestCase):
    """ConfigJIRAApi unit test stubs"""

    def setUp(self):
        self.api = ConfigJIRAApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_delete_configuration1(self):
        """Test case for delete_configuration1"""
        pass

    def test_get_configuration1(self):
        """Test case for get_configuration1"""
        pass

    def test_set_configuration1(self):
        """Test case for set_configuration1"""
        pass


if __name__ == "__main__":
    unittest.main()
