"""
    Sonatype Nexus IQ Server

    This documents the available APIs into [Sonatype Nexus IQ Server](https://www.sonatype.com/products/open-source-security-dependency-management) (also knwon as Nexus Lifecycle).   # noqa: E501

    OpenAPI spec version: 156

    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import unittest

import nexus_iq_sdk
from nexus_iq_sdk.models.api_policy_violation_stage_dto import (  # noqa: E501
    ApiPolicyViolationStageDTO,
)
from nexus_iq_sdk.rest import ApiException


class TestApiPolicyViolationStageDTO(unittest.TestCase):
    """ApiPolicyViolationStageDTO unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testApiPolicyViolationStageDTO(self):
        """Test ApiPolicyViolationStageDTO"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.api_policy_violation_stage_dto.ApiPolicyViolationStageDTO()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
