# coding: utf-8

"""
    Sonatype Nexus IQ Server

    This documents the available APIs into [Sonatype Nexus IQ Server](https://www.sonatype.com/products/open-source-security-dependency-management) (also knwon as Nexus Lifecycle).   # noqa: E501

    OpenAPI spec version: 156
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import nexus_iq_sdk
from nexus_iq_sdk.models.api_promote_scan_request_dtov2 import (  # noqa: E501
    ApiPromoteScanRequestDTOV2,
)
from nexus_iq_sdk.rest import ApiException


class TestApiPromoteScanRequestDTOV2(unittest.TestCase):
    """ApiPromoteScanRequestDTOV2 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testApiPromoteScanRequestDTOV2(self):
        """Test ApiPromoteScanRequestDTOV2"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.api_promote_scan_request_dtov2.ApiPromoteScanRequestDTOV2()  # noqa: E501
        pass


if __name__ == "__main__":
    unittest.main()
