"""
    Sonatype Nexus IQ Server

    This documents the available APIs into [Sonatype Nexus IQ Server](https://www.sonatype.com/products/open-source-security-dependency-management) (also knwon as Nexus Lifecycle).   # noqa: E501

    OpenAPI spec version: 156

    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import unittest

import nexus_iq_sdk
from nexus_iq_sdk.api.license_legal_metadata_api import (  # noqa: E501
    LicenseLegalMetadataApi,
)
from nexus_iq_sdk.rest import ApiException


class TestLicenseLegalMetadataApi(unittest.TestCase):
    """LicenseLegalMetadataApi unit test stubs"""

    def setUp(self):
        self.api = LicenseLegalMetadataApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_delete_attribution_report_template(self):
        """Test case for delete_attribution_report_template"""
        pass

    def test_get_all_attribution_report_templates(self):
        """Test case for get_all_attribution_report_templates"""
        pass

    def test_get_attribution_report_template_by_id(self):
        """Test case for get_attribution_report_template_by_id"""
        pass

    def test_get_license_legal_application_html_report(self):
        """Test case for get_license_legal_application_html_report"""
        pass

    def test_get_license_legal_application_report(self):
        """Test case for get_license_legal_application_report"""
        pass

    def test_get_license_legal_application_report1(self):
        """Test case for get_license_legal_application_report1"""
        pass

    def test_get_license_legal_component_report(self):
        """Test case for get_license_legal_component_report"""
        pass

    def test_get_license_legal_custom_application_html_report(self):
        """Test case for get_license_legal_custom_application_html_report"""
        pass

    def test_get_license_legal_custom_application_html_report1(self):
        """Test case for get_license_legal_custom_application_html_report1"""
        pass

    def test_get_license_legal_custom_multi_application_html_report1(self):
        """Test case for get_license_legal_custom_multi_application_html_report1"""
        pass

    def test_get_license_legal_multi_application_html_report(self):
        """Test case for get_license_legal_multi_application_html_report"""
        pass

    def test_get_license_legal_multi_application_report_from_active_user_filter(self):
        """Test case for get_license_legal_multi_application_report_from_active_user_filter"""
        pass

    def test_save_attribution_report_template(self):
        """Test case for save_attribution_report_template"""
        pass


if __name__ == '__main__':
    unittest.main()
