# coding: utf-8

"""
    Sonatype Nexus IQ Server

    This documents the available APIs into [Sonatype Nexus IQ Server](https://www.sonatype.com/products/open-source-security-dependency-management) (also knwon as Nexus Lifecycle).   # noqa: E501

    OpenAPI spec version: 156
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import nexus_iq_sdk
from nexus_iq_sdk.api.policy_waivers_api import PolicyWaiversApi  # noqa: E501
from nexus_iq_sdk.rest import ApiException


class TestPolicyWaiversApi(unittest.TestCase):
    """PolicyWaiversApi unit test stubs"""

    def setUp(self):
        self.api = PolicyWaiversApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_add_policy_waiver_by_policy_violation_id(self):
        """Test case for add_policy_waiver_by_policy_violation_id

        """
        pass

    def test_add_waiver_to_transitive_policy_violations_by_app_scan_component(self):
        """Test case for add_waiver_to_transitive_policy_violations_by_app_scan_component

        """
        pass

    def test_add_waiver_to_transitive_policy_violations_by_owner_stage_component(self):
        """Test case for add_waiver_to_transitive_policy_violations_by_owner_stage_component

        """
        pass

    def test_delete_policy_waiver(self):
        """Test case for delete_policy_waiver

        """
        pass

    def test_get_policy_waiver(self):
        """Test case for get_policy_waiver

        """
        pass

    def test_get_policy_waivers(self):
        """Test case for get_policy_waivers

        """
        pass

    def test_get_transitive_policy_waivers_by_app_scan_component(self):
        """Test case for get_transitive_policy_waivers_by_app_scan_component

        """
        pass


if __name__ == '__main__':
    unittest.main()
