"""
    Sonatype Nexus IQ Server

    This documents the available APIs into [Sonatype Nexus IQ Server](https://www.sonatype.com/products/open-source-security-dependency-management) (also knwon as Nexus Lifecycle).   # noqa: E501

    OpenAPI spec version: 156

    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import unittest

import nexus_iq_sdk
from nexus_iq_sdk.api.role_memberships_api import RoleMembershipsApi  # noqa: E501
from nexus_iq_sdk.rest import ApiException


class TestRoleMembershipsApi(unittest.TestCase):
    """RoleMembershipsApi unit test stubs"""

    def setUp(self):
        self.api = RoleMembershipsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_role_memberships_application_or_organization(self):
        """Test case for get_role_memberships_application_or_organization"""
        pass

    def test_get_role_memberships_global_or_repository_container(self):
        """Test case for get_role_memberships_global_or_repository_container"""
        pass

    def test_grant_role_membership_application_or_organization(self):
        """Test case for grant_role_membership_application_or_organization"""
        pass

    def test_grant_role_membership_global_or_repository_container(self):
        """Test case for grant_role_membership_global_or_repository_container"""
        pass

    def test_revoke_role_membership_application_or_organization(self):
        """Test case for revoke_role_membership_application_or_organization"""
        pass

    def test_revoke_role_membership_global_or_repository_container(self):
        """Test case for revoke_role_membership_global_or_repository_container"""
        pass


if __name__ == '__main__':
    unittest.main()
