"""
    Sonatype Nexus IQ Server

    This documents the available APIs into [Sonatype Nexus IQ Server](https://www.sonatype.com/products/open-source-security-dependency-management) (also knwon as Nexus Lifecycle).   # noqa: E501

    OpenAPI spec version: 156

    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import unittest

import nexus_iq_sdk
from nexus_iq_sdk.api.application_categories_api import (  # noqa: E501
    ApplicationCategoriesApi,
)
from nexus_iq_sdk.rest import ApiException


class TestApplicationCategoriesApi(unittest.TestCase):
    """ApplicationCategoriesApi unit test stubs"""

    def setUp(self):
        self.api = ApplicationCategoriesApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_add_tag(self):
        """Test case for add_tag"""
        pass

    def test_delete_tag(self):
        """Test case for delete_tag"""
        pass

    def test_get_applicable_tags(self):
        """Test case for get_applicable_tags"""
        pass

    def test_get_applicable_tags_by_application_public_id(self):
        """Test case for get_applicable_tags_by_application_public_id"""
        pass

    def test_get_application_applicable_tags(self):
        """Test case for get_application_applicable_tags"""
        pass

    def test_get_applied_policy_tags(self):
        """Test case for get_applied_policy_tags"""
        pass

    def test_get_applied_tags(self):
        """Test case for get_applied_tags"""
        pass

    def test_get_tags(self):
        """Test case for get_tags"""
        pass

    def test_get_tags_used_by_applications(self):
        """Test case for get_tags_used_by_applications"""
        pass

    def test_update_tag(self):
        """Test case for update_tag"""
        pass


if __name__ == '__main__':
    unittest.main()
