# coding: utf-8

"""
    Sonatype Nexus IQ Server

    This documents the available APIs into [Sonatype Nexus IQ Server](https://www.sonatype.com/products/open-source-security-dependency-management) (also knwon as Nexus Lifecycle).   # noqa: E501

    OpenAPI spec version: 156
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import nexus_iq_sdk
from nexus_iq_sdk.models.license_obligation_dto import LicenseObligationDTO  # noqa: E501
from nexus_iq_sdk.rest import ApiException


class TestLicenseObligationDTO(unittest.TestCase):
    """LicenseObligationDTO unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testLicenseObligationDTO(self):
        """Test LicenseObligationDTO"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.license_obligation_dto.LicenseObligationDTO()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
