# coding: utf-8

"""
    Sonatype Nexus IQ Server

    This documents the available APIs into [Sonatype Nexus IQ Server](https://www.sonatype.com/products/open-source-security-dependency-management) (also knwon as Nexus Lifecycle).   # noqa: E501

    OpenAPI spec version: 156
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import nexus_iq_sdk
from nexus_iq_sdk.api.source_control_api import SourceControlApi  # noqa: E501
from nexus_iq_sdk.rest import ApiException


class TestSourceControlApi(unittest.TestCase):
    """SourceControlApi unit test stubs"""

    def setUp(self):
        self.api = SourceControlApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_add_or_update_source_control(self):
        """Test case for add_or_update_source_control

        """
        pass

    def test_add_source_control(self):
        """Test case for add_source_control

        """
        pass

    def test_delete_source_control(self):
        """Test case for delete_source_control

        """
        pass

    def test_get_source_control1(self):
        """Test case for get_source_control1

        """
        pass

    def test_update_source_control(self):
        """Test case for update_source_control

        """
        pass


if __name__ == '__main__':
    unittest.main()
