"""
    Sonatype Nexus IQ Server

    This documents the available APIs into [Sonatype Nexus IQ Server](https://www.sonatype.com/products/open-source-security-dependency-management) (also knwon as Nexus Lifecycle).   # noqa: E501

    OpenAPI spec version: 156

    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import unittest

import nexus_iq_sdk
from nexus_iq_sdk.api.applications_api import ApplicationsApi  # noqa: E501
from nexus_iq_sdk.rest import ApiException


class TestApplicationsApi(unittest.TestCase):
    """ApplicationsApi unit test stubs"""

    def setUp(self):
        self.api = ApplicationsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_add_application(self):
        """Test case for add_application"""
        pass

    def test_clone_application(self):
        """Test case for clone_application"""
        pass

    def test_delete_application(self):
        """Test case for delete_application"""
        pass

    def test_get_application(self):
        """Test case for get_application"""
        pass

    def test_get_applications(self):
        """Test case for get_applications"""
        pass

    def test_get_applications_by_organization_id(self):
        """Test case for get_applications_by_organization_id"""
        pass

    def test_get_data(self):
        """Test case for get_data"""
        pass

    def test_get_dependency_tree(self):
        """Test case for get_dependency_tree"""
        pass

    def test_get_policy_violation_diff(self):
        """Test case for get_policy_violation_diff"""
        pass

    def test_get_policy_violations1(self):
        """Test case for get_policy_violations1"""
        pass

    def test_get_raw_data(self):
        """Test case for get_raw_data"""
        pass

    def test_move_application(self):
        """Test case for move_application"""
        pass

    def test_update_application(self):
        """Test case for update_application"""
        pass


if __name__ == '__main__':
    unittest.main()
