"""
    Sonatype Nexus IQ Server

    This documents the available APIs into [Sonatype Nexus IQ Server](https://www.sonatype.com/products/open-source-security-dependency-management) (also knwon as Nexus Lifecycle).   # noqa: E501

    OpenAPI spec version: 156

    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import unittest

import nexus_iq_sdk
from nexus_iq_sdk.api.config_saml_api import ConfigSAMLApi  # noqa: E501
from nexus_iq_sdk.rest import ApiException


class TestConfigSAMLApi(unittest.TestCase):
    """ConfigSAMLApi unit test stubs"""

    def setUp(self):
        self.api = ConfigSAMLApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_delete_saml_configuration(self):
        """Test case for delete_saml_configuration"""
        pass

    def test_get_metadata(self):
        """Test case for get_metadata"""
        pass

    def test_get_saml_configuration(self):
        """Test case for get_saml_configuration"""
        pass


if __name__ == '__main__':
    unittest.main()
