"""
    Sonatype Nexus IQ Server

    This documents the available APIs into [Sonatype Nexus IQ Server](https://www.sonatype.com/products/open-source-security-dependency-management) (also knwon as Nexus Lifecycle).   # noqa: E501

    OpenAPI spec version: 156

    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import unittest

import nexus_iq_sdk
from nexus_iq_sdk.api.config_proxy_server_api import ConfigProxyServerApi  # noqa: E501
from nexus_iq_sdk.rest import ApiException


class TestConfigProxyServerApi(unittest.TestCase):
    """ConfigProxyServerApi unit test stubs"""

    def setUp(self):
        self.api = ConfigProxyServerApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_delete_configuration3(self):
        """Test case for delete_configuration3"""
        pass

    def test_get_configuration3(self):
        """Test case for get_configuration3"""
        pass

    def test_set_configuration3(self):
        """Test case for set_configuration3"""
        pass


if __name__ == '__main__':
    unittest.main()
