"""
    Sonatype Nexus IQ Server

    This documents the available APIs into [Sonatype Nexus IQ Server](https://www.sonatype.com/products/open-source-security-dependency-management) (also knwon as Nexus Lifecycle).   # noqa: E501

    OpenAPI spec version: 156

    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import unittest

import nexus_iq_sdk
from nexus_iq_sdk.api.policy_violations_api import PolicyViolationsApi  # noqa: E501
from nexus_iq_sdk.rest import ApiException


class TestPolicyViolationsApi(unittest.TestCase):
    """PolicyViolationsApi unit test stubs"""

    def setUp(self):
        self.api = PolicyViolationsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_applicable_waivers(self):
        """Test case for get_applicable_waivers"""
        pass

    def test_get_cross_stage_policy_violation_by_constituent_id(self):
        """Test case for get_cross_stage_policy_violation_by_constituent_id"""
        pass

    def test_get_cross_stage_policy_violation_by_id(self):
        """Test case for get_cross_stage_policy_violation_by_id"""
        pass

    def test_get_policy_violations(self):
        """Test case for get_policy_violations"""
        pass

    def test_get_transitive_policy_violations_by_app_scan_component(self):
        """Test case for get_transitive_policy_violations_by_app_scan_component"""
        pass

    def test_get_transitive_policy_violations_by_owner_stage_component(self):
        """Test case for get_transitive_policy_violations_by_owner_stage_component"""
        pass


if __name__ == '__main__':
    unittest.main()
