"""
    Sonatype Nexus IQ Server

    This documents the available APIs into [Sonatype Nexus IQ Server](https://www.sonatype.com/products/open-source-security-dependency-management) (also knwon as Nexus Lifecycle).   # noqa: E501

    OpenAPI spec version: 156

    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import unittest

import nexus_iq_sdk
from nexus_iq_sdk.models.form_data_content_disposition import (  # noqa: E501
    FormDataContentDisposition,
)
from nexus_iq_sdk.rest import ApiException


class TestFormDataContentDisposition(unittest.TestCase):
    """FormDataContentDisposition unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testFormDataContentDisposition(self):
        """Test FormDataContentDisposition"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.form_data_content_disposition.FormDataContentDisposition()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
