# coding: utf-8

"""
    Sonatype Nexus IQ Server

    This documents the available APIs into [Sonatype Nexus IQ Server](https://www.sonatype.com/products/open-source-security-dependency-management) (also knwon as Nexus Lifecycle).   # noqa: E501

    OpenAPI spec version: 156
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import nexus_iq_sdk
from nexus_iq_sdk.api.security_overrides_api import SecurityOverridesApi  # noqa: E501
from nexus_iq_sdk.rest import ApiException


class TestSecurityOverridesApi(unittest.TestCase):
    """SecurityOverridesApi unit test stubs"""

    def setUp(self):
        self.api = SecurityOverridesApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_security_vulnerability_overrides(self):
        """Test case for get_security_vulnerability_overrides"""
        pass


if __name__ == "__main__":
    unittest.main()
