"""
    Sonatype Nexus IQ Server

    This documents the available APIs into [Sonatype Nexus IQ Server](https://www.sonatype.com/products/open-source-security-dependency-management) (also knwon as Nexus Lifecycle).   # noqa: E501

    OpenAPI spec version: 156

    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import unittest

import nexus_iq_sdk
from nexus_iq_sdk.api.firewall_api import FirewallApi  # noqa: E501
from nexus_iq_sdk.rest import ApiException


class TestFirewallApi(unittest.TestCase):
    """FirewallApi unit test stubs"""

    def setUp(self):
        self.api = FirewallApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_firewall_auto_unquarantine_config(self):
        """Test case for get_firewall_auto_unquarantine_config"""
        pass

    def test_get_firewall_unquarantine_summary(self):
        """Test case for get_firewall_unquarantine_summary"""
        pass

    def test_get_quarantine_list(self):
        """Test case for get_quarantine_list"""
        pass

    def test_get_quarantine_summary(self):
        """Test case for get_quarantine_summary"""
        pass

    def test_get_quarantined_component_view_anonymous_access(self):
        """Test case for get_quarantined_component_view_anonymous_access"""
        pass

    def test_get_unquarantine_list(self):
        """Test case for get_unquarantine_list"""
        pass

    def test_set_firewall_auto_unquarantine_config(self):
        """Test case for set_firewall_auto_unquarantine_config"""
        pass

    def test_set_quarantined_component_view_anonymous_access(self):
        """Test case for set_quarantined_component_view_anonymous_access"""
        pass


if __name__ == '__main__':
    unittest.main()
