"""
    Sonatype Nexus IQ Server

    This documents the available APIs into [Sonatype Nexus IQ Server](https://www.sonatype.com/products/open-source-security-dependency-management) (also knwon as Nexus Lifecycle).   # noqa: E501

    OpenAPI spec version: 156

    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import unittest

import nexus_iq_sdk
from nexus_iq_sdk.models.api_owner_artifactory_connection_dto import (  # noqa: E501
    ApiOwnerArtifactoryConnectionDTO,
)
from nexus_iq_sdk.rest import ApiException


class TestApiOwnerArtifactoryConnectionDTO(unittest.TestCase):
    """ApiOwnerArtifactoryConnectionDTO unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testApiOwnerArtifactoryConnectionDTO(self):
        """Test ApiOwnerArtifactoryConnectionDTO"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.api_owner_artifactory_connection_dto.ApiOwnerArtifactoryConnectionDTO()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
