"""
    Sonatype Nexus IQ Server

    This documents the available APIs into [Sonatype Nexus IQ Server](https://www.sonatype.com/products/open-source-security-dependency-management) (also knwon as Nexus Lifecycle).   # noqa: E501

    OpenAPI spec version: 156

    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import unittest

import nexus_iq_sdk
from nexus_iq_sdk.models.api_components_in_quarantine_dto import (  # noqa: E501
    ApiComponentsInQuarantineDTO,
)
from nexus_iq_sdk.rest import ApiException


class TestApiComponentsInQuarantineDTO(unittest.TestCase):
    """ApiComponentsInQuarantineDTO unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testApiComponentsInQuarantineDTO(self):
        """Test ApiComponentsInQuarantineDTO"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.api_components_in_quarantine_dto.ApiComponentsInQuarantineDTO()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
