# coding: utf-8

"""
    Sonatype Nexus IQ Server

    This documents the available APIs into [Sonatype Nexus IQ Server](https://www.sonatype.com/products/open-source-security-dependency-management) (also knwon as Nexus Lifecycle).   # noqa: E501

    OpenAPI spec version: 156
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import nexus_iq_sdk
from nexus_iq_sdk.api.components_api import ComponentsApi  # noqa: E501
from nexus_iq_sdk.rest import ApiException


class TestComponentsApi(unittest.TestCase):
    """ComponentsApi unit test stubs"""

    def setUp(self):
        self.api = ComponentsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_delete_component_label(self):
        """Test case for delete_component_label

        """
        pass

    def test_get_component_details(self):
        """Test case for get_component_details

        """
        pass

    def test_get_component_versions(self):
        """Test case for get_component_versions

        """
        pass

    def test_get_suggested_remediation_for_component(self):
        """Test case for get_suggested_remediation_for_component

        """
        pass

    def test_set_component_label(self):
        """Test case for set_component_label

        """
        pass


if __name__ == '__main__':
    unittest.main()
