# coding: utf-8

"""
    Sonatype Nexus IQ Server

    This documents the available APIs into [Sonatype Nexus IQ Server](https://www.sonatype.com/products/open-source-security-dependency-management) (also knwon as Nexus Lifecycle).   # noqa: E501

    OpenAPI spec version: 156
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import nexus_iq_sdk
from nexus_iq_sdk.api.user_tokens_api import UserTokensApi  # noqa: E501
from nexus_iq_sdk.rest import ApiException


class TestUserTokensApi(unittest.TestCase):
    """UserTokensApi unit test stubs"""

    def setUp(self):
        self.api = UserTokensApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_user_token(self):
        """Test case for create_user_token"""
        pass

    def test_delete_current_user_token(self):
        """Test case for delete_current_user_token"""
        pass

    def test_delete_user_token_by_user_code(self):
        """Test case for delete_user_token_by_user_code"""
        pass

    def test_get_user_token_by_username_and_realm_id(self):
        """Test case for get_user_token_by_username_and_realm_id"""
        pass

    def test_get_user_token_exists_for_current_user(self):
        """Test case for get_user_token_exists_for_current_user"""
        pass

    def test_get_user_tokens_by_created_between_and_realm_id(self):
        """Test case for get_user_tokens_by_created_between_and_realm_id"""
        pass

    def test_purge_user_tokens(self):
        """Test case for purge_user_tokens"""
        pass


if __name__ == "__main__":
    unittest.main()
