"""
    Sonatype Nexus IQ Server

    This documents the available APIs into [Sonatype Nexus IQ Server](https://www.sonatype.com/products/open-source-security-dependency-management) (also knwon as Nexus Lifecycle).   # noqa: E501

    OpenAPI spec version: 156

    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import unittest

import nexus_iq_sdk
from nexus_iq_sdk.models.applicable_context import ApplicableContext  # noqa: E501
from nexus_iq_sdk.rest import ApiException


class TestApplicableContext(unittest.TestCase):
    """ApplicableContext unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testApplicableContext(self):
        """Test ApplicableContext"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.applicable_context.ApplicableContext()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
