# coding: utf-8

"""
    Sonatype Nexus IQ Server

    This documents the available APIs into [Sonatype Nexus IQ Server](https://www.sonatype.com/products/open-source-security-dependency-management) (also knwon as Nexus Lifecycle).   # noqa: E501

    OpenAPI spec version: 156
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import nexus_iq_sdk
from nexus_iq_sdk.api.search_api import SearchApi  # noqa: E501
from nexus_iq_sdk.rest import ApiException


class TestSearchApi(unittest.TestCase):
    """SearchApi unit test stubs"""

    def setUp(self):
        self.api = SearchApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_search_index_async(self):
        """Test case for create_search_index_async

        """
        pass

    def test_get_export_results(self):
        """Test case for get_export_results

        """
        pass

    def test_search_component(self):
        """Test case for search_component

        """
        pass

    def test_search_index(self):
        """Test case for search_index

        """
        pass


if __name__ == '__main__':
    unittest.main()
