# coding: utf-8

"""
    Sonatype Nexus IQ Server

    This documents the available APIs into [Sonatype Nexus IQ Server](https://www.sonatype.com/products/open-source-security-dependency-management) (also knwon as Nexus Lifecycle).   # noqa: E501

    OpenAPI spec version: 156
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import nexus_iq_sdk
from nexus_iq_sdk.api.config_mail_api import ConfigMailApi  # noqa: E501
from nexus_iq_sdk.rest import ApiException


class TestConfigMailApi(unittest.TestCase):
    """ConfigMailApi unit test stubs"""

    def setUp(self):
        self.api = ConfigMailApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_delete_configuration2(self):
        """Test case for delete_configuration2

        """
        pass

    def test_get_configuration2(self):
        """Test case for get_configuration2

        """
        pass

    def test_set_configuration2(self):
        """Test case for set_configuration2

        """
        pass

    def test_test_configuration(self):
        """Test case for test_configuration

        """
        pass


if __name__ == '__main__':
    unittest.main()
